### ISSUE TITLE
sealed trait CustomErrors

### ISSUE THREAD

**Issue by Donatas-L** [arnasbr/regions-locations-task#2]
It's really `sealed trait CustomError` (not plural)

**Comment by Donatas-L** [comment]
Another issue is that you don't even use `msg` anywhere. For example:

```
  case class ParseError(msg: String) extends CustomErrors {
    override def toString: String = "Failed to parse from file"
  }
```

You create `case class ParseError`, which contains valuable information in `msg: String`, but that variable is never used.

**Comment by arnasbr** [comment]
Renamed to `CustomError`, implemented more detailed error messages using the `msg: String`
